// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5AZsjj9eg93EUlulXSc8yZTuNI_MBtWw',
    appId: '1:1089391987104:web:74f2aa2fdcd63b069f3cc5',
    messagingSenderId: '1089391987104',
    projectId: 'eventease-555',
    authDomain: 'eventease-555.firebaseapp.com',
    storageBucket: 'eventease-555.firebasestorage.app',
    measurementId: 'G-XGXP13RBJ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl2z3kGWIiqKOJTxMrO5cJU4yHCAyK9jk',
    appId: '1:1089391987104:android:11a3cfe67cfae4119f3cc5',
    messagingSenderId: '1089391987104',
    projectId: 'eventease-555',
    storageBucket: 'eventease-555.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP9RFdnWYPQnJpf3KPjGxPN6lTmlPvmBI',
    appId: '1:1089391987104:ios:298ad9e4009da59f9f3cc5',
    messagingSenderId: '1089391987104',
    projectId: 'eventease-555',
    storageBucket: 'eventease-555.firebasestorage.app',
    iosBundleId: 'com.eventease.eventease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP9RFdnWYPQnJpf3KPjGxPN6lTmlPvmBI',
    appId: '1:1089391987104:ios:298ad9e4009da59f9f3cc5',
    messagingSenderId: '1089391987104',
    projectId: 'eventease-555',
    storageBucket: 'eventease-555.firebasestorage.app',
    iosBundleId: 'com.eventease.eventease',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5AZsjj9eg93EUlulXSc8yZTuNI_MBtWw',
    appId: '1:1089391987104:web:50d67fef9952559d9f3cc5',
    messagingSenderId: '1089391987104',
    projectId: 'eventease-555',
    authDomain: 'eventease-555.firebaseapp.com',
    storageBucket: 'eventease-555.firebasestorage.app',
    measurementId: 'G-Z2Z7ZBYT2Q',
  );
}
