import 'package:flutter/material.dart';

/// Color roles exported from the EventEase Material Theme Builder palette.
abstract final class EventEaseColorSchemes {
  static const light = ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFFB91C1C),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFFFDAD6),
    onPrimaryContainer: Color(0xFF410002),
    secondary: Color(0xFF775652),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFFFDAD6),
    onSecondaryContainer: Color(0xFF2C1512),
    tertiary: Color(0xFF705C2E),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFFCDFA6),
    onTertiaryContainer: Color(0xFF261A00),
    error: Color(0xFFBA1A1A),
    onError: Color(0xFFFFFFFF),
    errorContainer: Color(0xFFFFDAD6),
    onErrorContainer: Color(0xFF410002),
    surface: Color(0xFFFFF8F7),
    onSurface: Color(0xFF231918),
    surfaceContainerHighest: Color(0xFFF5DDDA),
    onSurfaceVariant: Color(0xFF534341),
    outline: Color(0xFF857370),
    outlineVariant: Color(0xFFD8C2BE),
    shadow: Color(0xFF000000),
    scrim: Color(0xFF000000),
    inverseSurface: Color(0xFF392E2C),
    onInverseSurface: Color(0xFFFFEDEA),
    inversePrimary: Color(0xFFFFB4A9),
    surfaceTint: Color(0xFFB91C1C),
  );

  static const dark = ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFFFFB4A9),
    onPrimary: Color(0xFF680005),
    primaryContainer: Color(0xFF92000A),
    onPrimaryContainer: Color(0xFFFFDAD6),
    secondary: Color(0xFFE7BDB7),
    onSecondary: Color(0xFF442925),
    secondaryContainer: Color(0xFF5D3F3B),
    onSecondaryContainer: Color(0xFFFFDAD6),
    tertiary: Color(0xFFDFC48C),
    onTertiary: Color(0xFF3D2F05),
    tertiaryContainer: Color(0xFF554519),
    onTertiaryContainer: Color(0xFFFCDFA6),
    error: Color(0xFFFFB4AB),
    onError: Color(0xFF690005),
    errorContainer: Color(0xFF93000A),
    onErrorContainer: Color(0xFFFFDAD6),
    surface: Color(0xFF1A1110),
    onSurface: Color(0xFFF0DFDC),
    surfaceContainerHighest: Color(0xFF534341),
    onSurfaceVariant: Color(0xFFD8C2BE),
    outline: Color(0xFFA08C89),
    outlineVariant: Color(0xFF534341),
    shadow: Color(0xFF000000),
    scrim: Color(0xFF000000),
    inverseSurface: Color(0xFFF0DFDC),
    onInverseSurface: Color(0xFF392E2C),
    inversePrimary: Color(0xFFB91C1C),
    surfaceTint: Color(0xFFFFB4A9),
  );
}
